### ISSUE TITLE
[8.0] [stock_picking_package_preparation] fields weight and net_weight in view raise an Assertion

### ISSUE THREAD

**Issue by OpenCode** [OCA/stock-logistics-workflow#147]
If I insert weight and net_weight field on stock_picking_package_preparation form view, when I try to create a new record, I obtain this:

```
Traceback (most recent call last):
  File "ROOT_PATH/Odoo/OCB/openerp/http.py", line 537, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "ROOT_PATH/Odoo/OCB/openerp/http.py", line 574, in dispatch
    result = self._call_function(**self.params)
  File "ROOT_PATH/Odoo/OCB/openerp/http.py", line 310, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "ROOT_PATH/Odoo/OCB/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "ROOT_PATH/Odoo/OCB/openerp/http.py", line 307, in checked_call
    return self.endpoint(*a, **kw)
  File "ROOT_PATH/Odoo/OCB/openerp/http.py", line 803, in __call__
    return self.method(*args, **kw)
  File "ROOT_PATH/Odoo/OCB/openerp/http.py", line 403, in response_wrap
    response = f(*args, **kw)
  File "ROOT_PATH/Odoo/OCB/addons/web/controllers/main.py", line 944, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "ROOT_PATH/Odoo/OCB/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "ROOT_PATH/Odoo/OCB/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "ROOT_PATH/Odoo/OCB/openerp/api.py", line 363, in old_api
    result = method(recs, *args, **kwargs)
  File "ROOT_PATH/Odoo/OCB/openerp/models.py", line 5874, in onchange
    newval = record[name]
  File "ROOT_PATH/Odoo/OCB/openerp/models.py", line 5572, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "ROOT_PATH/Odoo/OCB/openerp/fields.py", line 820, in __get__
    self.determine_draft_value(record)
  File "ROOT_PATH/Odoo/OCB/openerp/fields.py", line 928, in determine_draft_value
    self._compute_value(record)
  File "ROOT_PATH/Odoo/OCB/openerp/fields.py", line 867, in _compute_value
    self.compute(records)
  File "ROOT_PATH/Odoo/OCB/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "ROOT_PATH/Odoo/OCB/openerp/api.py", line 398, in new_api
    result = [method(rec, *args, **kwargs) for rec in self]
  File "ROOT_PATH/Odoo/ExternalRepo/stock-logistics-workflow/stock_picking_package_preparation/model/stock_picking_package_preparation.py", line 141, in _compute_weight
    quants = quant_model.browse(package.get_content())
  File "ROOT_PATH/Odoo/OCB/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "ROOT_PATH/Odoo/OCB/openerp/api.py", line 547, in new_api
    result = method(self._model, cr, uid, self.ids, *args, **kwargs)
  File "ROOT_PATH/Odoo/OCB/addons/stock/stock.py", line 3931, in get_content
    child_package_ids = self.search(cr, uid, [('id', 'child_of', ids)], context=context)
  File "ROOT_PATH/Odoo/OCB/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "ROOT_PATH/Odoo/OCB/openerp/models.py", line 1643, in search
    return self._search(cr, user, args, offset=offset, limit=limit, order=order, context=context, count=count)
  File "ROOT_PATH/Odoo/OCB/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "ROOT_PATH/Odoo/OCB/openerp/models.py", line 4639, in _search
    query = self._where_calc(cr, user, args, context=context)
  File "ROOT_PATH/Odoo/OCB/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "ROOT_PATH/Odoo/OCB/openerp/models.py", line 4464, in _where_calc
    where_clause, where_params = e.to_sql()
  File "ROOT_PATH/Odoo/OCB/openerp/osv/expression.py", line 1256, in to_sql
    assert len(stack) == 1
AssertionError
```

**Comment by OpenCode** [comment]
Solved by https://github.com/OCA/stock-logistics-workflow/commit/b0455f8a329bb00d4a7b59141c04e7e8a7658ef3
