### ISSUE TITLE
[10.0] stock_delivery_internal crashes

### ISSUE THREAD

**Issue by ellis** [OCA/stock-logistics-workflow#371]
Hi Guys - I found your addon through the Odoo website.  Is it supposed to be working yet?  I'm getting the following error when I click on [Validate] for an internal transfer with an `Internal` carrier selected.

```
Traceback (most recent call last):
  File "/home/odoo/odoo/server/odoo/http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/odoo/server/odoo/http.py", line 677, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/odoo/server/odoo/http.py", line 333, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/odoo/server/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/odoo/server/odoo/http.py", line 326, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/odoo/server/odoo/http.py", line 935, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/odoo/server/odoo/http.py", line 506, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/odoo/server/addons/web/controllers/main.py", line 889, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/odoo/odoo/server/addons/web/controllers/main.py", line 877, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo/odoo/server/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/home/odoo/odoo/server/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/odoo/odoo/server/addons/stock/wizard/stock_immediate_transfer.py", line 36, in process
    self.pick_id.do_transfer()
  File "/home/odoo/odoo/server/addons/delivery/models/stock_picking.py", line 117, in do_transfer
    self.send_to_shipper()
  File "/home/odoo/odoo/server/addons/delivery/models/stock_picking.py", line 155, in send_to_shipper
    res = self.carrier_id.send_shipping(self)[0]
TypeError: 'NoneType' object has no attribute '__getitem__'
```

Does that trace give you any clue about the source of the error?  Anything else I should try or information I should provide?

**Comment by rousseldenis** [comment]
@woodbrettm 

This is confirmed

**Comment by woodbrettm** [comment]
@lasley
