### ISSUE TITLE
stock_ownership_availability_rules: traceback on install

### ISSUE THREAD

**Issue by gurneyalex** [OCA/stock-logistics-workflow#73]
Steps to reproduce:
1. use OCB branch (did not check with official)
2. first install `stock_route_sales_team` and `stock_dropshipping_dual_invoice` with demo data
3. Then install `stock_ownership_availability_rules`

I get:

```
openerp.service.server: Failed to initialize database `test_ocb_oca_70`.
Traceback (most recent call last):
  File "work/oerp/odoo/odoo/openerp/service/server.py", line 909, in preload_registries
    registry = RegistryManager.new(dbname, update_module=update_module)
  File "work/oerp/odoo/odoo/openerp/modules/registry.py", line 366, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "work/oerp/odoo/odoo/openerp/modules/loading.py", line 355, in load_modules
    loaded_modules, update_module)
  File "work/oerp/odoo/odoo/openerp/modules/loading.py", line 255, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "work/oerp/odoo/odoo/openerp/modules/loading.py", line 150, in load_module_graph
    getattr(py_module, pre_init)(cr)
  File "work/OCA/stock-logistics-workflow/stock_ownership_availability_rules/__init__.py", line 11, in fill_quant_owner
    orphan_quants = env['stock.quant'].search([('owner_id', '=', False)])
  File "work/oerp/odoo/odoo/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "work/oerp/odoo/odoo/openerp/api.py", line 462, in new_api
    result = method(self._model, cr, uid, *args, **kwargs)
  File "work/oerp/odoo/odoo/openerp/models.py", line 1649, in search
    return self._search(cr, user, args, offset=offset, limit=limit, order=order, context=context, count=count)
  File "work/oerp/odoo/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "work/oerp/odoo/odoo/openerp/models.py", line 4602, in _search
    query = self._where_calc(cr, user, args, context=context)
  File "work/oerp/odoo/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "work/oerp/odoo/odoo/openerp/models.py", line 4415, in _where_calc
    if 'active' in self._fields and active_test and context.get('active_test', True):
AttributeError: 'stock.quant' object has no attribute '_fields'
```

**Comment by gurneyalex** [comment]
@lepistone could you look into this when you get some spare time?

**Comment by lepistone** [comment]
I checked: the module contains a pre-init hook that creates a new `Environment` and then work with it. This doesn't seem to work anymore, because the models are not initialized (`_fields` is `{}`).

It's probably less of a pain to rewrite that logic in SQL than find out what broke that.
